### ISSUE TITLE
报错NotImplementedError

### ISSUE THREAD

**Issue by lihongbo-pei** [Lei00764/AMSeWL-R#1]
作者你好，我运行你们的代码出现错误如下，这是什么原因引起的，应该怎么解决：
```
Traceback (most recent call last):
  File "D:\PycharmProjects\AMSeWL-R\YOLOv8-R\ultralytics\engine\model.py", line 746, in _smart_load
    return self.task_map[self.task][key]
KeyError: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PycharmProjects\AMSeWL-R\YOLOv8-R\train.py", line 7, in <module>
    model = YOLO(r".\ultralytics\cfg\models\yolov8-R.yaml")
  File "D:\PycharmProjects\AMSeWL-R\YOLOv8-R\ultralytics\engine\model.py", line 133, in __init__
    self._new(model, task=task)
  File "D:\PycharmProjects\AMSeWL-R\YOLOv8-R\ultralytics\engine\model.py", line 198, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "D:\PycharmProjects\AMSeWL-R\YOLOv8-R\ultralytics\engine\model.py", line 750, in _smart_load
    raise NotImplementedError(
NotImplementedError: WARNING  'YOLO' model does not support '_new' mode for 'None' task yet.
```

**Comment by Lei00764** [comment]
感谢你关注我的项目！我测试了一下，貌似没问题耶。你的ultralytics和其他库版本跟我提供的requirements.txt中的一致吗？
在网上查询了一下你的报错，参考：https://github.com/ultralytics/ultralytics/issues/5272 
希望对你有帮助！
